name: Enviar alerta para o Discord

on:
  push:
    branches:
      - main

jobs:
  enviar-alerta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Enviar alerta para o Discord
        uses: Ilshidur/action-discord@v0.4.0
        with:
          args: |
            🚀 Novo commit no branch main!
            - Autor: ${{ github.actor }}
            - Mensagem: ${{ github.event.head_commit.message }}
            - Commit: ${{ github.sha }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

