name: my CD test 

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Rodar deploy 
        run: echo "Deploy executado com sucessoooo"
